version: 0.0
os: linux
files:
  - source: /
    destination: /home/ubuntu/parcelport
hooks:
  BeforeInstall:
    - location: deploy/before_install.sh
      timeout: 300
      runas: root
  AfterInstall:
    - location: deploy/after_install.sh
      timeout: 300
      runas: root
  ApplicationStart:
    - location: deploy/start_server.sh
      timeout: 300
      runas: root
